# Generated by Django 5.0.1 on 2024-01-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mgmt', models.CharField(max_length=50)),
                ('moi', models.CharField(blank=True, max_length=50, null=True)),
                ('cat', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=20)),
                ('cluster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('block_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district_name', models.CharField(max_length=255)),
                ('school_type', models.CharField(max_length=50)),
                ('assembly_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parliament_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('bus', models.CharField(blank=True, max_length=255, null=True)),
                ('coord', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
